katalog/urls.py
# TODO: Implement Routings Here
from katalog.views import show_catalog_item
from django.urls import path

app_name = 'catalog'

urlpatterns = [
    path('', show_catalog_item, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

# TODO: Implement Routings Here

todolist/urls.py
from todolist.views import marker, register, login_user, logout_user, show_todolist, savetask, delete_task, show_todolist_json, add_todolist_json,  delete_task_ajax,  update_task_ajax
from django.urls import path


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', savetask, name='savetask'),
    path('marker/<int:id>', marker, name='marker'),
    path('delete/<int:id>', delete_task, name='delete'),
    path('json/', show_todolist_json, name='todolist_json'),
    path('add/', add_todolist_json, name='add_todolist_json '),
    path('delete/<id>', delete_task_ajax, name='delete-task-ajax'),
    path('update/<id>', update_task_ajax, name='update-task-ajax'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE) # ketika user di hapus, maka task juga akan terhapus 
    date = models.DateField()
    description = models.TextField()

    is_finished = models.BooleanField(default=False) # bonus

todolist/forms.py
from asyncio import Task
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

todolist/views.py
from http.client import HTTPResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from todolist.models import Task
from django.contrib.auth.decorators import login_required
from todolist.forms import TaskForm
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from datetime import date
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.all().filter(user=request.user)

    context = {
        'nama' : request.user,
        # 'todolist': data_todolist,
    }

    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def savetask(request):
    task = Task(user=request.user, date=date.today())
    form = TaskForm(request.POST or None, instance=task)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/todolist/')

    context = {}

    return render(request, 'form-task.html', context)

def marker(request, id):
   task = Task.objects.get(id = id)
   task.is_finished = not(task.is_finished)
   task.save()
   return redirect('todolist:show_todolist')

def delete_task(request, id):
    task = Task.objects.get(id = id)
    task.delete()
    return redirect('todolist:show_todolist')

def show_todolist_json(request):
    data_todolist = Task.objects.all().filter(user=request.user)

    return HttpResponse(serializers.serialize("json", data_todolist), content_type = "application/json")

def add_todolist_json(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax and request.method == "POST":
        task = Task(user=request.user, date=date.today())
        form = TaskForm(request.POST or None, instance=task)
        if form.is_valid():
            form.save()
            return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login')
@csrf_exempt
def delete_task_ajax(request, id):
    if request.method == "DELETE":
        task = Task.objects.get(id = id)
        task.delete()
    return HttpResponse(status=202)

@login_required(login_url='/todolist/login')
@csrf_exempt
def update_task_ajax(request, id):
    if request.method == "PATCH":
        task = get_object_or_404(Task, id = id)
        task.is_finished = not task.is_finished
        task.save()
    
    result = {
        'fields':{
            'title': task.title,
            'description': task.description,
            'is_finished': task.is_finished,
            'date': task.date,
            },
            'pk': task.pk
        }
        
    return JsonResponse(result)

    

todolist/templates/form-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create task</title>
{% endblock meta %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<section class="gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">create task</h2>
                <p class="text-white-50 mb-5">Please enter your title and description!</p>

                <form method="post" action="">
                    {% csrf_token %}
                    <div class="form-outline form-white mb-4">
                        <input type="text" id="typeEmailX" class="form-control form-control-lg" name="title" />
                        <label class="form-label" for="typeEmailX">Title</label>
                      </div>
        
                      <div class="form-outline form-white mb-4">
                        <input type="text" id="typePasswordX" class="form-control form-control-lg" name="description"/>
                        <label class="form-label" for="typePasswordX">Description</label>
                      </div>
        
                      <button class="btn btn-outline-light btn-lg px-5" type="submit">Submit</button>
                </form>

  
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<section class="gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">💗Login💗</h2>
                <p class="text-white-50 mb-5">Please enter your username and password!</p>

                <form method="post" action="">
                    {% csrf_token %}
                    <div class="form-outline form-white mb-4">
                        <input type="text" id="typeEmailX" class="form-control form-control-lg" name="username" />
                        <label class="form-label" for="typeEmailX">Username</label>
                      </div>
        
                      <div class="form-outline form-white mb-4">
                        <input type="password" id="typePasswordX" class="form-control form-control-lg" name="password"/>
                        <label class="form-label" for="typePasswordX">Password</label>
                      </div>
        
                      <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>
        
                      <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                </form>
  
                <div class="d-flex justify-content-center text-center mt-4 pt-1">
                  <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                  <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                  <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                </div>
  
              </div>
  
              <div>
                <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                </p>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

{% load static %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-lg-9 col-xl-7">
          <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">💗Registration Form💗</h3>
              <form method="POST" action="">
                {%csrf_token%}
  
                <div class="row">
                  <div class="col-md-6 mb-4">
  
                    <div class="form-outline">
                      <input type="text" id="firstName" name="username" class="form-control form-control-lg" />
                      <label class="form-label" for="firstName">Username</label>
                    </div>
  
                  </div>
                </div>
  
                <div class="row">
                    <div class="form-outline">
                        <input type="password" id="password1" name="password1" class="form-control form-control-lg" />
                        <label class="form-label" for="password1">Password</label>
                     </div>
                    <div class="form-outline">
                        <input type="password" id="password2" name="password2" class="form-control form-control-lg" />
                        <label class="form-label" for="password2">Enter your password again!</label>
                    </div>
                </div>
  
                <div class="mt-4 pt-2">
                  <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
                </div>
  
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}

{% load static %} 

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 <!-- <script type="text/JavaScript" src="{% static 'get.js' %}"></script> -->
 <script>
  // using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
 </script>

 <script>
        function deleteCard(id) {
            $.ajax({
                url: `/todolist/delete/${id}`,
                type: 'DELETE',
                headers: {
          "X-CSRFToken": getCookie("csrftoken")
        },
                success: function (result) {
                    $('#card-body').empty()
                    $.get('/todolist/json', function (data) {
    data.map((singleData) =>
        $('#card-body').append(`<div class="col">
       <div class="card" style="width: 18rem;">
         <div class="card-body">
 
           <h5 class="card-title">${singleData.fields.user}</h5>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.date}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.title}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.is_finished}</h6>
           <p class="card-text">${singleData.fields.description}</p>
           <a href="/todolist/marker/${singleData.pk}   " class="card-link"><button>Update</button></a>
           <a  onclick="deleteCard(${singleData.pk})" class="card-link"><button>Delete</button></a>
         </div>
       </div>
     </div>`)
    );
    });
                }
            });
        }
 </script>

<script>
   function updateCard(id) {
            $.ajax({
                url: `/todolist/update/${id}`,
                type: 'PATCH',
                headers: {
          "X-CSRFToken": getCookie("csrftoken")
        },
                success: function (data) {
                  $('#card-body').empty()
                    $.get('/todolist/json', function (data) {
    data.map((singleData) =>
        $('#card-body').append(`<div class="col">
       <div class="card" style="width: 18rem;">
         <div class="card-body">
 
           <h5 class="card-title">${singleData.fields.user}</h5>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.date}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.title}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.is_finished}</h6>
           <p class="card-text">${singleData.fields.description}</p>
           <a onclick="updateCard(${singleData.pk})"   " class="card-link"><button>Update</button></a>
           <a  onclick="deleteCard(${singleData.pk})" class="card-link"><button>Delete</button></a>
         </div>
       </div>
     </div>`)
    );
    });
                   
                }
            });
        }
</script>

 <script>
  $(document).ready(function () {

$.get('/todolist/json', function (data) {
data.map((singleData) =>
    $('#card-body').append(`<div class="col">
   <div class="card" style="width: 18rem;">
     <div class="card-body">

       <h5 class="card-title">${singleData.fields.user}</h5>
       <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.date}</h6>
       <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.title}</h6>
       <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.is_finished}</h6>
       <p class="card-text">${singleData.fields.description}</p>
       <a onclick="updateCard(${singleData.pk})"  " class="card-link"><button>Update</button></a>
       <a  onclick="deleteCard(${singleData.pk})" class="card-link"><button>Delete</button></a>
     </div>
   </div>
 </div>`)
);
});
});
 </script>

<script>
  $(document).ready(function() {
    $('#task-form').submit(function(e) {
      e.preventDefault();
      $.ajax({
        url: "/todolist/add/",
        type: "POST",
        headers: {
          "X-CSRFToken": getCookie("csrftoken")
        },
        data: {
          title : $('#task-title').val(),
          description : $("#task-desc").val()
        },
        success: function(){
          $('.col').remove();
          $('#exampleModal').modal('hide');
          $.get('/todolist/json', function (data) {
    data.map((singleData) =>
        $('#card-body').append(`<div class="col">
       <div class="card" style="width: 18rem;">
         <div class="card-body">
 
           <h5 class="card-title">${singleData.fields.user}</h5>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.date}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.title}</h6>
           <h6 class="card-subtitle mb-2 text-muted">${singleData.fields.is_finished}</h6>
           <p class="card-text">${singleData.fields.description}</p>
           <a onclick="updateCard(${singleData.pk})"  " class="card-link"><button>Update</button></a>
           <a  onclick="deleteCard(${singleData.pk})" class="card-link"><button>Delete</button></a>
         </div>
       </div>
     </div>`)
    );
    });
        },
        error: function(data){
          alert("error")
        }
      });
    });
  })
</script>

<center style="color: rgb(242, 129, 189)">

    <h1> 💗Welcome back!💗 </h1>

    <h5>Name: </h5>
    <p>{{nama}}</p>

    <button><a href="{% url 'todolist:savetask' %}">Create task</a></button>
    <button><a href="{% url 'todolist:logout' %}">Logout</a></button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New message</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="task-form">
              <div class="mb-3">
                <label for="recipient-name" class="col-form-label">Title:</label>
                <input type="text" class="form-control" id="task-title">
              </div>
              <div class="mb-3">
                <label for="message-text" class="col-form-label">Description:</label>
                <textarea class="form-control" id="task-desc"></textarea>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" >Submit</button>
              </div>
  
            </form>

          </div>
          
        </div>
      </div>
    </div>

</center>

<center>
         <!-- Button trigger modal -->
         <button type="button" class="" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Add task
        </button>
</center>


<style> body{
    background-color:rgb(15, 2, 9);
}
.table{
    margin: 0 auto;
}

.card {
  background: linear-gradient(to bottom, #ea5bc2 0%, #f9dcec 100%);

}

.card:hover{
  transform: scale(1.1);

  }
  .card{
      transition: transform .5s;
  }

</style>


<center>

  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4" id="card-body">
      <!-- {% comment %} Add the data below this line {% endcomment %}
      {% for task in todolist %}
  
      <div class="col">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
  
            <h5 class="card-title">{{ task.user }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ task.date }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">{{ task.title }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">{{ task.is_finished }}</h6>
            <p class="card-text">{{task.description}}</p>
            <a href="{% url 'todolist:marker' task.id %}" class="card-link"><button>Update</button></a>
            <a href="{% url 'todolist:delete' task.id %}" class="card-link"><button>Delete</button></a>
          </div>
        </div>
      </div>
        
      {%endfor%}   -->
    </div>
  
  </div>

</center>

 {% endblock content %}